# Generated by Django 5.2.1 on 2025-05-24 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='userId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='blog_app.users'),
        ),
    ]
