# Generated by Django 5.2.1 on 2025-05-24 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_blogpost_userid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
