# Generated by Django 5.2.1 on 2025-05-31 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0012_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog_app.blogpost')),
                ('userId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blog_likes', to='blog_app.user')),
            ],
        ),
    ]
