# Generated by Django 5.2.1 on 2025-07-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0013_bloglikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Phones', 'Phones'), ('Laptops', 'Laptops'), ('Watches', 'Watches'), ('TVs', 'Tvs'), ('Radios', 'Radios')], default='Accessories', max_length=50),
        ),
    ]
